package mcp

import (
	"encoding/xml"
	"fmt"
	"log"
	"regexp"
	"strings"

	"github.com/google/uuid"
)

// ToolCall represents a single tool invocation requested by the model.
// The model emits these inside <tool_call> XML blocks in its response.
type ToolCall struct {
	ID         string            // stable call ID generated by Hearth, not the model
	ToolID     string            // e.g. "web_search", "email:send"
	Parameters map[string]string // parsed key-value pairs from <parameters>
	RawXML     string            // original XML block for audit purposes
}

// ToolResult is the outcome of executing a ToolCall.
type ToolResult struct {
	CallID  string
	ToolID  string
	Content string // free-form text output from the MCP server
	IsError bool
	Error   string // set when IsError is true
}

// xmlToolCallDoc is the parsed representation of a <tool_call> block.
type xmlToolCallDoc struct {
	XMLName    xml.Name         `xml:"tool_call"`
	ToolID     string           `xml:"tool_id"`
	Parameters xmlParametersDoc `xml:"parameters"`
}

type xmlParametersDoc struct {
	Params []xmlParam `xml:",any"`
}

type xmlParam struct {
	XMLName xml.Name
	Value   string `xml:",chardata"`
}

var toolCallPattern = regexp.MustCompile(`(?s)<tool_call>.*?</tool_call>`)

// ParseToolCalls scans response text for <tool_call>...</tool_call> blocks
// and returns the parsed calls plus the response text with those blocks
// stripped (the remaining text is the visible prose to deliver to the user
// as an interim message, or discard if empty).
func ParseToolCalls(response string) (calls []ToolCall, prose string, err error) {
	matches := toolCallPattern.FindAllStringIndex(response, -1)
	if len(matches) == 0 {
		return nil, response, nil
	}

	for _, loc := range matches {
		raw := response[loc[0]:loc[1]]
		call, parseErr := parseToolCallBlock(raw)
		if parseErr != nil {
			log.Printf("mcp: skipping malformed tool_call block: %v", parseErr)
			continue
		}
		calls = append(calls, call)
	}

	prose = toolCallPattern.ReplaceAllString(response, "")
	prose = strings.TrimSpace(prose)

	return calls, prose, nil
}

func parseToolCallBlock(raw string) (ToolCall, error) {
	var doc xmlToolCallDoc
	if err := xml.Unmarshal([]byte(raw), &doc); err != nil {
		return ToolCall{}, fmt.Errorf("xml.Unmarshal: %w", err)
	}

	params := make(map[string]string, len(doc.Parameters.Params))
	for _, p := range doc.Parameters.Params {
		params[p.XMLName.Local] = strings.TrimSpace(p.Value)
	}

	return ToolCall{
		ID:         uuid.New().String(),
		ToolID:     doc.ToolID,
		Parameters: params,
		RawXML:     raw,
	}, nil
}
