// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateRoomData, CreateRoomErrors, CreateRoomResponses, GetAgentData, GetAgentErrors, GetAgentResponses, GetMeData, GetMeErrors, GetMeResponses, GetRoomData, GetRoomErrors, GetRoomResponses, ListAgentsData, ListAgentsErrors, ListAgentsResponses, ListMessagesData, ListMessagesErrors, ListMessagesResponses, ListRoomsData, ListRoomsErrors, ListRoomsResponses, PreviewContextData, PreviewContextErrors, PreviewContextResponses, SendMessageData, SendMessageErrors, SendMessageResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List loaded agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>) => (options?.client ?? client).get<ListAgentsResponses, ListAgentsErrors, ThrowOnError>({ url: '/api/agents', ...options });

/**
 * Get agent details
 */
export const getAgent = <ThrowOnError extends boolean = false>(options: Options<GetAgentData, ThrowOnError>) => (options.client ?? client).get<GetAgentResponses, GetAgentErrors, ThrowOnError>({ url: '/api/agents/{name}', ...options });

/**
 * Get current user
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({ url: '/api/me', ...options });

/**
 * List rooms
 */
export const listRooms = <ThrowOnError extends boolean = false>(options?: Options<ListRoomsData, ThrowOnError>) => (options?.client ?? client).get<ListRoomsResponses, ListRoomsErrors, ThrowOnError>({ url: '/api/rooms', ...options });

/**
 * Create a new room
 */
export const createRoom = <ThrowOnError extends boolean = false>(options: Options<CreateRoomData, ThrowOnError>) => (options.client ?? client).post<CreateRoomResponses, CreateRoomErrors, ThrowOnError>({
    url: '/api/rooms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get room details
 */
export const getRoom = <ThrowOnError extends boolean = false>(options: Options<GetRoomData, ThrowOnError>) => (options.client ?? client).get<GetRoomResponses, GetRoomErrors, ThrowOnError>({ url: '/api/rooms/{room_id}', ...options });

/**
 * Preview agent context window
 */
export const previewContext = <ThrowOnError extends boolean = false>(options: Options<PreviewContextData, ThrowOnError>) => (options.client ?? client).get<PreviewContextResponses, PreviewContextErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/agents/{agent_name}/context-preview', ...options });

/**
 * List messages in a room
 */
export const listMessages = <ThrowOnError extends boolean = false>(options: Options<ListMessagesData, ThrowOnError>) => (options.client ?? client).get<ListMessagesResponses, ListMessagesErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/messages', ...options });

/**
 * Send a message to a room
 */
export const sendMessage = <ThrowOnError extends boolean = false>(options: Options<SendMessageData, ThrowOnError>) => (options.client ?? client).post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
    url: '/api/rooms/{room_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List pending tool-call confirmations for a room
 */
export const listConfirmations = <ThrowOnError extends boolean = false>(options: Options<{ url: string; path: { room_id: number | string } }, ThrowOnError>) =>
    (options.client ?? client).get<{ confirmations: import('./types.gen').ConfirmationResponse[] }, unknown, ThrowOnError>({ url: '/api/rooms/{room_id}/confirmations', ...options });

/**
 * Respond to a pending tool-call confirmation
 */
export const respondConfirmation = <ThrowOnError extends boolean = false>(options: Options<{
    url: string;
    path: { room_id: number | string; node_id: string };
    body: { action: 'allow' | 'deny' | 'revise'; args?: string; feedback?: string };
}, ThrowOnError>) =>
    (options.client ?? client).post<void, unknown, ThrowOnError>({
        url: '/api/rooms/{room_id}/confirmations/{node_id}',
        ...options,
        headers: { 'Content-Type': 'application/json', ...options.headers },
    });
