// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CompactRoomData, CompactRoomErrors, CompactRoomResponses, CreateRoomData, CreateRoomErrors, CreateRoomResponses, EditMessageData, EditMessageErrors, EditMessageResponses, GetAgentDagData, GetAgentDagErrors, GetAgentDagResponses, GetAgentData, GetAgentErrors, GetAgentMemoryData, GetAgentMemoryErrors, GetAgentMemoryResponses, GetAgentResponses, GetCompactionStatsData, GetCompactionStatsErrors, GetCompactionStatsResponses, GetMeData, GetMeErrors, GetMeResponses, GetRoomData, GetRoomErrors, GetRoomResponses, ListAgentsData, ListAgentsErrors, ListAgentsResponses, ListConfirmationsData, ListConfirmationsErrors, ListConfirmationsResponses, ListMessagesData, ListMessagesErrors, ListMessagesResponses, ListRoomsData, ListRoomsErrors, ListRoomsResponses, PreviewContextData, PreviewContextErrors, PreviewContextResponses, RespondConfirmationData, RespondConfirmationErrors, RespondConfirmationResponses, RetryMessageData, RetryMessageErrors, RetryMessageResponses, SendMessageData, SendMessageErrors, SendMessageResponses, SwitchBranchData, SwitchBranchErrors, SwitchBranchResponses, UpdateRoomData, UpdateRoomErrors, UpdateRoomResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List loaded agents
 */
export const listAgents = <ThrowOnError extends boolean = false>(options?: Options<ListAgentsData, ThrowOnError>) => (options?.client ?? client).get<ListAgentsResponses, ListAgentsErrors, ThrowOnError>({ url: '/api/agents', ...options });

/**
 * Get an agent's current request DAG
 */
export const getAgentDag = <ThrowOnError extends boolean = false>(options: Options<GetAgentDagData, ThrowOnError>) => (options.client ?? client).get<GetAgentDagResponses, GetAgentDagErrors, ThrowOnError>({ url: '/api/agents/{agent_name}/dag', ...options });

/**
 * Inspect an agent's memory and daily notes by clearance
 */
export const getAgentMemory = <ThrowOnError extends boolean = false>(options: Options<GetAgentMemoryData, ThrowOnError>) => (options.client ?? client).get<GetAgentMemoryResponses, GetAgentMemoryErrors, ThrowOnError>({ url: '/api/agents/{agent_name}/memory', ...options });

/**
 * Get agent details
 */
export const getAgent = <ThrowOnError extends boolean = false>(options: Options<GetAgentData, ThrowOnError>) => (options.client ?? client).get<GetAgentResponses, GetAgentErrors, ThrowOnError>({ url: '/api/agents/{name}', ...options });

/**
 * Get current user
 */
export const getMe = <ThrowOnError extends boolean = false>(options?: Options<GetMeData, ThrowOnError>) => (options?.client ?? client).get<GetMeResponses, GetMeErrors, ThrowOnError>({ url: '/api/me', ...options });

/**
 * List rooms
 */
export const listRooms = <ThrowOnError extends boolean = false>(options?: Options<ListRoomsData, ThrowOnError>) => (options?.client ?? client).get<ListRoomsResponses, ListRoomsErrors, ThrowOnError>({ url: '/api/rooms', ...options });

/**
 * Create a new room
 */
export const createRoom = <ThrowOnError extends boolean = false>(options: Options<CreateRoomData, ThrowOnError>) => (options.client ?? client).post<CreateRoomResponses, CreateRoomErrors, ThrowOnError>({
    url: '/api/rooms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get room details
 */
export const getRoom = <ThrowOnError extends boolean = false>(options: Options<GetRoomData, ThrowOnError>) => (options.client ?? client).get<GetRoomResponses, GetRoomErrors, ThrowOnError>({ url: '/api/rooms/{room_id}', ...options });

/**
 * Update room metadata
 */
export const updateRoom = <ThrowOnError extends boolean = false>(options: Options<UpdateRoomData, ThrowOnError>) => (options.client ?? client).patch<UpdateRoomResponses, UpdateRoomErrors, ThrowOnError>({
    url: '/api/rooms/{room_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Preview agent context window
 */
export const previewContext = <ThrowOnError extends boolean = false>(options: Options<PreviewContextData, ThrowOnError>) => (options.client ?? client).get<PreviewContextResponses, PreviewContextErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/agents/{agent_name}/context-preview', ...options });

/**
 * Compact an agent's transcript in a room
 */
export const compactRoom = <ThrowOnError extends boolean = false>(options: Options<CompactRoomData, ThrowOnError>) => (options.client ?? client).post<CompactRoomResponses, CompactRoomErrors, ThrowOnError>({
    url: '/api/rooms/{room_id}/compact',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Report an agent's compaction state for a room
 */
export const getCompactionStats = <ThrowOnError extends boolean = false>(options: Options<GetCompactionStatsData, ThrowOnError>) => (options.client ?? client).get<GetCompactionStatsResponses, GetCompactionStatsErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/compaction', ...options });

/**
 * List pending tool-call confirmations for a room
 */
export const listConfirmations = <ThrowOnError extends boolean = false>(options: Options<ListConfirmationsData, ThrowOnError>) => (options.client ?? client).get<ListConfirmationsResponses, ListConfirmationsErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/confirmations', ...options });

/**
 * Respond to a pending tool-call confirmation
 */
export const respondConfirmation = <ThrowOnError extends boolean = false>(options: Options<RespondConfirmationData, ThrowOnError>) => (options.client ?? client).post<RespondConfirmationResponses, RespondConfirmationErrors, ThrowOnError>({
    url: '/api/rooms/{room_id}/confirmations/{node_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List messages in a room
 */
export const listMessages = <ThrowOnError extends boolean = false>(options: Options<ListMessagesData, ThrowOnError>) => (options.client ?? client).get<ListMessagesResponses, ListMessagesErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/messages', ...options });

/**
 * Send a message to a room
 */
export const sendMessage = <ThrowOnError extends boolean = false>(options: Options<SendMessageData, ThrowOnError>) => (options.client ?? client).post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
    url: '/api/rooms/{room_id}/messages',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Fork a sibling of a message with edited content
 */
export const editMessage = <ThrowOnError extends boolean = false>(options: Options<EditMessageData, ThrowOnError>) => (options.client ?? client).post<EditMessageResponses, EditMessageErrors, ThrowOnError>({
    url: '/api/rooms/{room_id}/messages/{message_id}/edit',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Regenerate an assistant message as a new sibling
 */
export const retryMessage = <ThrowOnError extends boolean = false>(options: Options<RetryMessageData, ThrowOnError>) => (options.client ?? client).post<RetryMessageResponses, RetryMessageErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/messages/{message_id}/retry', ...options });

/**
 * Switch the active branch to a sibling message
 */
export const switchBranch = <ThrowOnError extends boolean = false>(options: Options<SwitchBranchData, ThrowOnError>) => (options.client ?? client).post<SwitchBranchResponses, SwitchBranchErrors, ThrowOnError>({ url: '/api/rooms/{room_id}/messages/{message_id}/switch', ...options });
