// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type ActorResponse = {
    /**
     * Clearance tier
     */
    clearance: number;
    /**
     * Actor identifier
     */
    id: string;
    /**
     * Display name
     */
    name: string;
    /**
     * Actor type
     */
    type: string;
};

export type AgentDailyNoteResponse = {
    content: string;
    date: string;
};

export type AgentMemoryLevelResponse = {
    clearance: number;
    memory: string;
    notes: Array<AgentDailyNoteResponse> | null;
};

export type AgentResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether agent is currently loaded
     */
    active: boolean;
    /**
     * Agent clearance tier
     */
    clearance: number;
    /**
     * Agent name
     */
    name: string;
    /**
     * Primary model ID
     */
    primary_model: string;
    /**
     * Agent role description
     */
    role_description: string;
    /**
     * Routine model ID
     */
    routine_model: string;
    /**
     * Sensitive model ID
     */
    sensitive_model: string;
};

export type CompactRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Agent whose transcript to compact
     */
    agent: string;
    /**
     * Target size in bytes; omit for the configured default
     */
    target?: number;
};

export type CompactRoomResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    compacted: boolean;
};

export type CompactionStatsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    bytes: number;
    messages: number;
    offset: number;
    target: number;
    trigger: number;
};

export type ConfirmationResponse = {
    /**
     * Name of the agent waiting for confirmation
     */
    agent_name: string;
    /**
     * JSON-encoded tool arguments
     */
    args: string;
    /**
     * Unique node ID — used in the respond endpoint
     */
    node_id: string;
    /**
     * Why confirmation is required (e.g. blp_write_down, permission_confirmation)
     */
    reason: string;
    /**
     * Room the confirmation belongs to
     */
    room_id: number;
    /**
     * Tool the agent wants to call
     */
    tool_name: string;
};

export type ContextMessageResponse = {
    /**
     * Message content
     */
    content: string;
    /**
     * Tool or actor name if provided
     */
    name?: string;
    /**
     * Message role
     */
    role: string;
};

export type ContextToolResponse = {
    /**
     * Tool data-classification clearance tier
     */
    clearance: number;
    /**
     * Tool name
     */
    name: string;
    /**
     * Tool FRSN resource identifier
     */
    resource: string;
};

export type CreateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Room clearance tier (default 5)
     */
    clearance: number;
    /**
     * Human-readable room name
     */
    name?: string;
    /**
     * Actor IDs (user:<name> or agent:<name>)
     */
    participant_ids: Array<string> | null;
};

export type DagNode = {
    blocked_by?: Array<string> | null;
    children?: Array<string> | null;
    created_at?: string;
    id: string;
    kind?: string;
    label?: string;
    settled_at?: string;
    started_at?: string;
    state: string;
    waiting_on?: string;
};

export type EditMessageRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * New message body
     */
    content: string;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetAgentDagResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * DAG nodes in insertion order
     */
    nodes: Array<DagNode> | null;
};

export type GetAgentMemoryResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    agent_name: string;
    levels: Array<AgentMemoryLevelResponse> | null;
};

export type GetContextPreviewResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Total byte size of assembled message content
     */
    assembled_bytes: number;
    /**
     * Current compaction cursor offset
     */
    compaction_offset: number;
    messages: Array<ContextMessageResponse> | null;
    /**
     * Tool definitions the agent would receive
     */
    tools: Array<ContextToolResponse> | null;
};

export type ListAgentsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    agents: Array<AgentResponse> | null;
};

export type ListConfirmationsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    confirmations: Array<ConfirmationResponse> | null;
};

export type ListMessagesResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    messages: Array<MessageResponse> | null;
};

export type ListRoomsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    rooms: Array<RoomResponse> | null;
};

export type MessageResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Classification tier
     */
    clearance_tag: number;
    /**
     * Message body
     */
    content: string;
    /**
     * Message ID
     */
    id: number;
    /**
     * Room this message belongs to
     */
    room_id: number;
    /**
     * Actor who sent this message
     */
    sender: ActorResponse;
    /**
     * IDs of all messages at this fork (incl. self), ordered; present only when this message has alternative branches
     */
    sibling_ids?: Array<number> | null;
    /**
     * Message timestamp
     */
    timestamp: string;
    /**
     * Correlating tool call ID for tool_result messages
     */
    tool_call_id?: string;
    /**
     * Structured tool calls for tool_call messages
     */
    tool_calls?: Array<ToolCallRecord> | null;
    /**
     * Tool identifier for tool_result messages
     */
    tool_name?: string;
    /**
     * Message type
     */
    type: string;
    /**
     * Token usage for agent responses
     */
    usage?: Usage;
};

export type RespondConfirmationRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * allow | deny | revise
     */
    action: string;
    /**
     * Edited JSON arguments (action=allow only)
     */
    args?: string;
    /**
     * Revision guidance for the agent (action=revise only)
     */
    feedback?: string;
};

export type RoomResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Room clearance tier
     */
    clearance: number;
    /**
     * Room creation time
     */
    created_at: string;
    /**
     * Unique room ID
     */
    id: number;
    /**
     * Human-readable room name
     */
    name: string;
    /**
     * Room participants
     */
    participants: Array<ActorResponse> | null;
    /**
     * Last update time
     */
    updated_at: string;
};

export type SendMessageRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Message body
     */
    content: string;
    /**
     * Actor ID of the sender
     */
    sender: string;
};

export type ToolCallRecord = {
    arguments?: string;
    id?: string;
    tool_name: string;
};

export type UpdateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Human-readable room name
     */
    name: string;
};

export type Usage = {
    input_tokens: number;
    output_tokens: number;
};

export type UserResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * User ID
     */
    id: string;
    /**
     * Display name
     */
    name: string;
    /**
     * User role
     */
    role: string;
};

export type AgentResponseWritable = {
    /**
     * Whether agent is currently loaded
     */
    active: boolean;
    /**
     * Agent clearance tier
     */
    clearance: number;
    /**
     * Agent name
     */
    name: string;
    /**
     * Primary model ID
     */
    primary_model: string;
    /**
     * Agent role description
     */
    role_description: string;
    /**
     * Routine model ID
     */
    routine_model: string;
    /**
     * Sensitive model ID
     */
    sensitive_model: string;
};

export type CompactRoomRequestBodyWritable = {
    /**
     * Agent whose transcript to compact
     */
    agent: string;
    /**
     * Target size in bytes; omit for the configured default
     */
    target?: number;
};

export type CompactRoomResponseBodyWritable = {
    compacted: boolean;
};

export type CompactionStatsResponseBodyWritable = {
    bytes: number;
    messages: number;
    offset: number;
    target: number;
    trigger: number;
};

export type CreateRoomRequestBodyWritable = {
    /**
     * Room clearance tier (default 5)
     */
    clearance: number;
    /**
     * Human-readable room name
     */
    name?: string;
    /**
     * Actor IDs (user:<name> or agent:<name>)
     */
    participant_ids: Array<string> | null;
};

export type EditMessageRequestBodyWritable = {
    /**
     * New message body
     */
    content: string;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetAgentDagResponseBodyWritable = {
    /**
     * DAG nodes in insertion order
     */
    nodes: Array<DagNode> | null;
};

export type GetAgentMemoryResponseBodyWritable = {
    agent_name: string;
    levels: Array<AgentMemoryLevelResponse> | null;
};

export type GetContextPreviewResponseBodyWritable = {
    /**
     * Total byte size of assembled message content
     */
    assembled_bytes: number;
    /**
     * Current compaction cursor offset
     */
    compaction_offset: number;
    messages: Array<ContextMessageResponse> | null;
    /**
     * Tool definitions the agent would receive
     */
    tools: Array<ContextToolResponse> | null;
};

export type ListAgentsResponseBodyWritable = {
    agents: Array<AgentResponseWritable> | null;
};

export type ListConfirmationsResponseBodyWritable = {
    confirmations: Array<ConfirmationResponse> | null;
};

export type ListMessagesResponseBodyWritable = {
    messages: Array<MessageResponseWritable> | null;
};

export type ListRoomsResponseBodyWritable = {
    rooms: Array<RoomResponseWritable> | null;
};

export type MessageResponseWritable = {
    /**
     * Classification tier
     */
    clearance_tag: number;
    /**
     * Message body
     */
    content: string;
    /**
     * Message ID
     */
    id: number;
    /**
     * Room this message belongs to
     */
    room_id: number;
    /**
     * Actor who sent this message
     */
    sender: ActorResponse;
    /**
     * IDs of all messages at this fork (incl. self), ordered; present only when this message has alternative branches
     */
    sibling_ids?: Array<number> | null;
    /**
     * Message timestamp
     */
    timestamp: string;
    /**
     * Correlating tool call ID for tool_result messages
     */
    tool_call_id?: string;
    /**
     * Structured tool calls for tool_call messages
     */
    tool_calls?: Array<ToolCallRecord> | null;
    /**
     * Tool identifier for tool_result messages
     */
    tool_name?: string;
    /**
     * Message type
     */
    type: string;
    /**
     * Token usage for agent responses
     */
    usage?: Usage;
};

export type RespondConfirmationRequestBodyWritable = {
    /**
     * allow | deny | revise
     */
    action: string;
    /**
     * Edited JSON arguments (action=allow only)
     */
    args?: string;
    /**
     * Revision guidance for the agent (action=revise only)
     */
    feedback?: string;
};

export type RoomResponseWritable = {
    /**
     * Room clearance tier
     */
    clearance: number;
    /**
     * Room creation time
     */
    created_at: string;
    /**
     * Unique room ID
     */
    id: number;
    /**
     * Human-readable room name
     */
    name: string;
    /**
     * Room participants
     */
    participants: Array<ActorResponse> | null;
    /**
     * Last update time
     */
    updated_at: string;
};

export type SendMessageRequestBodyWritable = {
    /**
     * Message body
     */
    content: string;
    /**
     * Actor ID of the sender
     */
    sender: string;
};

export type UpdateRoomRequestBodyWritable = {
    /**
     * Human-readable room name
     */
    name: string;
};

export type UserResponseWritable = {
    /**
     * User ID
     */
    id: string;
    /**
     * Display name
     */
    name: string;
    /**
     * User role
     */
    role: string;
};

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type ListAgentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors];

export type ListAgentsResponses = {
    /**
     * OK
     */
    200: ListAgentsResponseBody;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type GetAgentDagData = {
    body?: never;
    path: {
        /**
         * Agent name
         */
        agent_name: string;
    };
    query?: never;
    url: '/api/agents/{agent_name}/dag';
};

export type GetAgentDagErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentDagError = GetAgentDagErrors[keyof GetAgentDagErrors];

export type GetAgentDagResponses = {
    /**
     * OK
     */
    200: GetAgentDagResponseBody;
};

export type GetAgentDagResponse = GetAgentDagResponses[keyof GetAgentDagResponses];

export type GetAgentMemoryData = {
    body?: never;
    path: {
        /**
         * Agent name
         */
        agent_name: string;
    };
    query?: never;
    url: '/api/agents/{agent_name}/memory';
};

export type GetAgentMemoryErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentMemoryError = GetAgentMemoryErrors[keyof GetAgentMemoryErrors];

export type GetAgentMemoryResponses = {
    /**
     * OK
     */
    200: GetAgentMemoryResponseBody;
};

export type GetAgentMemoryResponse = GetAgentMemoryResponses[keyof GetAgentMemoryResponses];

export type GetAgentData = {
    body?: never;
    path: {
        /**
         * Agent name
         */
        name: string;
    };
    query?: never;
    url: '/api/agents/{name}';
};

export type GetAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * OK
     */
    200: AgentResponse;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by participant actor ID
         */
        participant?: string;
        /**
         * Max rooms to return
         */
        limit?: number;
        /**
         * Offset for pagination
         */
        offset?: number;
    };
    url: '/api/rooms';
};

export type ListRoomsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRoomsError = ListRoomsErrors[keyof ListRoomsErrors];

export type ListRoomsResponses = {
    /**
     * OK
     */
    200: ListRoomsResponseBody;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type CreateRoomData = {
    body: CreateRoomRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type CreateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateRoomError = CreateRoomErrors[keyof CreateRoomErrors];

export type CreateRoomResponses = {
    /**
     * OK
     */
    200: RoomResponse;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type GetRoomData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}';
};

export type GetRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetRoomError = GetRoomErrors[keyof GetRoomErrors];

export type GetRoomResponses = {
    /**
     * OK
     */
    200: RoomResponse;
};

export type GetRoomResponse = GetRoomResponses[keyof GetRoomResponses];

export type UpdateRoomData = {
    body: UpdateRoomRequestBodyWritable;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}';
};

export type UpdateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type UpdateRoomError = UpdateRoomErrors[keyof UpdateRoomErrors];

export type UpdateRoomResponses = {
    /**
     * OK
     */
    200: RoomResponse;
};

export type UpdateRoomResponse = UpdateRoomResponses[keyof UpdateRoomResponses];

export type PreviewContextData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
        /**
         * Agent name
         */
        agent_name: string;
    };
    query?: {
        /**
         * Include cross-room feed
         */
        include_cross_room?: boolean;
        /**
         * Include queued interjections
         */
        include_interjections?: boolean;
    };
    url: '/api/rooms/{room_id}/agents/{agent_name}/context-preview';
};

export type PreviewContextErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PreviewContextError = PreviewContextErrors[keyof PreviewContextErrors];

export type PreviewContextResponses = {
    /**
     * OK
     */
    200: GetContextPreviewResponseBody;
};

export type PreviewContextResponse = PreviewContextResponses[keyof PreviewContextResponses];

export type CompactRoomData = {
    body: CompactRoomRequestBodyWritable;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}/compact';
};

export type CompactRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CompactRoomError = CompactRoomErrors[keyof CompactRoomErrors];

export type CompactRoomResponses = {
    /**
     * OK
     */
    200: CompactRoomResponseBody;
};

export type CompactRoomResponse = CompactRoomResponses[keyof CompactRoomResponses];

export type GetCompactionStatsData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: {
        /**
         * Agent whose transcript to inspect
         */
        agent?: string;
    };
    url: '/api/rooms/{room_id}/compaction';
};

export type GetCompactionStatsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetCompactionStatsError = GetCompactionStatsErrors[keyof GetCompactionStatsErrors];

export type GetCompactionStatsResponses = {
    /**
     * OK
     */
    200: CompactionStatsResponseBody;
};

export type GetCompactionStatsResponse = GetCompactionStatsResponses[keyof GetCompactionStatsResponses];

export type ListConfirmationsData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}/confirmations';
};

export type ListConfirmationsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListConfirmationsError = ListConfirmationsErrors[keyof ListConfirmationsErrors];

export type ListConfirmationsResponses = {
    /**
     * OK
     */
    200: ListConfirmationsResponseBody;
};

export type ListConfirmationsResponse = ListConfirmationsResponses[keyof ListConfirmationsResponses];

export type RespondConfirmationData = {
    body: RespondConfirmationRequestBodyWritable;
    path: {
        /**
         * Room ID
         */
        room_id: number;
        /**
         * Confirmation node ID
         */
        node_id: string;
    };
    query?: never;
    url: '/api/rooms/{room_id}/confirmations/{node_id}';
};

export type RespondConfirmationErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RespondConfirmationError = RespondConfirmationErrors[keyof RespondConfirmationErrors];

export type RespondConfirmationResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RespondConfirmationResponse = RespondConfirmationResponses[keyof RespondConfirmationResponses];

export type ListMessagesData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: {
        /**
         * Max messages to return
         */
        limit?: number;
        /**
         * Cursor: only messages before this RFC3339 timestamp
         */
        before?: string;
    };
    url: '/api/rooms/{room_id}/messages';
};

export type ListMessagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
    /**
     * OK
     */
    200: ListMessagesResponseBody;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type SendMessageData = {
    body: SendMessageRequestBodyWritable;
    path: {
        /**
         * Room ID
         */
        room_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}/messages';
};

export type SendMessageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];

export type EditMessageData = {
    body: EditMessageRequestBodyWritable;
    path: {
        /**
         * Room ID
         */
        room_id: number;
        /**
         * Message to edit (forks a sibling)
         */
        message_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}/messages/{message_id}/edit';
};

export type EditMessageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type EditMessageError = EditMessageErrors[keyof EditMessageErrors];

export type EditMessageResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type EditMessageResponse = EditMessageResponses[keyof EditMessageResponses];

export type RetryMessageData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
        /**
         * Assistant message to regenerate
         */
        message_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}/messages/{message_id}/retry';
};

export type RetryMessageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type RetryMessageError = RetryMessageErrors[keyof RetryMessageErrors];

export type RetryMessageResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RetryMessageResponse = RetryMessageResponses[keyof RetryMessageResponses];

export type SwitchBranchData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: number;
        /**
         * Message to make the active branch at its fork
         */
        message_id: number;
    };
    query?: never;
    url: '/api/rooms/{room_id}/messages/{message_id}/switch';
};

export type SwitchBranchErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SwitchBranchError = SwitchBranchErrors[keyof SwitchBranchErrors];

export type SwitchBranchResponses = {
    /**
     * No Content
     */
    204: void;
};

export type SwitchBranchResponse = SwitchBranchResponses[keyof SwitchBranchResponses];
