// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

export type ActorResponse = {
    /**
     * Clearance tier
     */
    clearance: number;
    /**
     * Actor identifier
     */
    id: string;
    /**
     * Display name
     */
    name: string;
    /**
     * Actor type
     */
    type: string;
};

export type AgentResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Whether agent is currently loaded
     */
    active: boolean;
    /**
     * Agent clearance tier
     */
    clearance: number;
    /**
     * Agent name
     */
    name: string;
    /**
     * Primary model ID
     */
    primary_model: string;
    /**
     * Agent role description
     */
    role_description: string;
    /**
     * Routine model ID
     */
    routine_model: string;
    /**
     * Sensitive model ID
     */
    sensitive_model: string;
};

export type ContextMessageResponse = {
    /**
     * Message content
     */
    content: string;
    /**
     * Tool or actor name if provided
     */
    name?: string;
    /**
     * Message role
     */
    role: string;
};

export type CreateRoomRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
      * Room clearance tier (default 5)
     */
    clearance: number;
    /**
     * Actor IDs (user:<name> or agent:<name>)
     */
    participant_ids: Array<string> | null;
    /**
     * Protocol-specific configuration (JSON)
     */
    protocol_config?: unknown;
};

export type ErrorDetail = {
    /**
     * Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id'
     */
    location?: string;
    /**
     * Error message text
     */
    message?: string;
    /**
     * The value at the given location
     */
    value?: unknown;
};

export type ErrorModel = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetContextPreviewResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Total byte size of assembled message content
     */
    assembled_bytes: number;
    /**
     * Current compaction cursor offset
     */
    compaction_offset: number;
    messages: Array<ContextMessageResponse> | null;
};

export type ListAgentsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    agents: Array<AgentResponse> | null;
};

export type ListMessagesResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    messages: Array<MessageResponse> | null;
};

export type ListRoomsResponseBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    rooms: Array<RoomResponse> | null;
};

export type MessageResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Classification tier
     */
    clearance_tag: number;
    /**
     * Message body
     */
    content: string;
    /**
     * Per-room message number (primary key)
     */
    number: number;
    /**
     * Room this message belongs to
     */
    room_id: number;
    /**
     * Actor who sent this message
     */
    sender: ActorResponse;
    /**
     * Message timestamp
     */
    timestamp: string;
    /**
     * Message type
     */
    type: string;
    /**
     * Token usage for agent responses
     */
    usage?: { input_tokens: number; output_tokens: number };
    /**
     * Structured tool calls for tool_call messages
     */
    tool_calls?: Array<{ id?: string; tool_name: string; arguments?: string }>;
    /**
     * Correlating tool call ID for tool_result messages
     */
    tool_call_id?: string;
    /**
     * Tool identifier for tool_result messages
     */
    tool_name?: string;
};

export type ConfirmationResponse = {
    node_id: string;
    agent_name: string;
    room_id: number;
    tool_name: string;
    args: string;
    reason: string;
};

export type RoomResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Max clearance tier
     */
    clearance: number;
    /**
     * Room creation time
     */
    created_at: string;
    /**
     * Unique room ID
     */
    id: string;
    /**
     * Room participants
     */
    participants: Array<ActorResponse> | null;
    /**
     * Protocol configuration
     */
    protocol_config?: unknown;
    /**
     * Last update time
     */
    updated_at: string;
};

export type SendMessageRequestBody = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * Message body
     */
    content: string;
    /**
     * Actor ID of the sender
     */
    sender: string;
};

export type UserResponse = {
    /**
     * A URL to the JSON Schema for this object.
     */
    readonly $schema?: string;
    /**
     * User ID
     */
    id: string;
    /**
     * Display name
     */
    name: string;
    /**
     * User role
     */
    role: string;
};

export type AgentResponseWritable = {
    /**
     * Whether agent is currently loaded
     */
    active: boolean;
    /**
     * Agent clearance tier
     */
    clearance: number;
    /**
     * Agent name
     */
    name: string;
    /**
     * Primary model ID
     */
    primary_model: string;
    /**
     * Agent role description
     */
    role_description: string;
    /**
     * Routine model ID
     */
    routine_model: string;
    /**
     * Sensitive model ID
     */
    sensitive_model: string;
};

export type CreateRoomRequestBodyWritable = {
    /**
      * Room clearance tier (default 5)
     */
    clearance: number;
    /**
     * Actor IDs (user:<name> or agent:<name>)
     */
    participant_ids: Array<string> | null;
    /**
     * Protocol-specific configuration (JSON)
     */
    protocol_config?: unknown;
};

export type ErrorModelWritable = {
    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    detail?: string;
    /**
     * Optional list of individual error details
     */
    errors?: Array<ErrorDetail> | null;
    /**
     * A URI reference that identifies the specific occurrence of the problem.
     */
    instance?: string;
    /**
     * HTTP status code
     */
    status?: number;
    /**
     * A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
     */
    title?: string;
    /**
     * A URI reference to human-readable documentation for the error.
     */
    type?: string;
};

export type GetContextPreviewResponseBodyWritable = {
    /**
     * Total byte size of assembled message content
     */
    assembled_bytes: number;
    /**
     * Current compaction cursor offset
     */
    compaction_offset: number;
    messages: Array<ContextMessageResponse> | null;
};

export type ListAgentsResponseBodyWritable = {
    agents: Array<AgentResponseWritable> | null;
};

export type ListMessagesResponseBodyWritable = {
    messages: Array<MessageResponseWritable> | null;
};

export type ListRoomsResponseBodyWritable = {
    rooms: Array<RoomResponseWritable> | null;
};

export type MessageResponseWritable = {
    /**
     * Classification tier
     */
    clearance_tag: number;
    /**
     * Message body
     */
    content: string;
    /**
     * Unique message ID
     */
    id: string;
    /**
     * Room this message belongs to
     */
    room_id: string;
    /**
     * Actor who sent this message
     */
    sender: ActorResponse;
    /**
     * Message timestamp
     */
    timestamp: string;
    /**
     * Message type
     */
    type: string;
};

export type RoomResponseWritable = {
    /**
     * Max clearance tier
     */
    clearance: number;
    /**
     * Room creation time
     */
    created_at: string;
    /**
     * Unique room ID
     */
    id: string;
    /**
     * Room participants
     */
    participants: Array<ActorResponse> | null;
    /**
     * Protocol configuration
     */
    protocol_config?: unknown;
    /**
     * Last update time
     */
    updated_at: string;
};

export type SendMessageRequestBodyWritable = {
    /**
     * Message body
     */
    content: string;
    /**
     * Actor ID of the sender
     */
    sender: string;
};

export type UserResponseWritable = {
    /**
     * User ID
     */
    id: string;
    /**
     * Display name
     */
    name: string;
    /**
     * User role
     */
    role: string;
};

export type ListAgentsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/agents';
};

export type ListAgentsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors];

export type ListAgentsResponses = {
    /**
     * OK
     */
    200: ListAgentsResponseBody;
};

export type ListAgentsResponse = ListAgentsResponses[keyof ListAgentsResponses];

export type GetAgentData = {
    body?: never;
    path: {
        /**
         * Agent name
         */
        name: string;
    };
    query?: never;
    url: '/api/agents/{name}';
};

export type GetAgentErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetAgentError = GetAgentErrors[keyof GetAgentErrors];

export type GetAgentResponses = {
    /**
     * OK
     */
    200: AgentResponse;
};

export type GetAgentResponse = GetAgentResponses[keyof GetAgentResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/me';
};

export type GetMeErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: UserResponse;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type ListRoomsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Filter by participant actor ID
         */
        participant?: string;
        /**
         * Filter by protocol type
         */
        protocol?: string;
        /**
         * Max rooms to return
         */
        limit?: number;
        /**
         * Offset for pagination
         */
        offset?: number;
    };
    url: '/api/rooms';
};

export type ListRoomsErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListRoomsError = ListRoomsErrors[keyof ListRoomsErrors];

export type ListRoomsResponses = {
    /**
     * OK
     */
    200: ListRoomsResponseBody;
};

export type ListRoomsResponse = ListRoomsResponses[keyof ListRoomsResponses];

export type CreateRoomData = {
    body: CreateRoomRequestBodyWritable;
    path?: never;
    query?: never;
    url: '/api/rooms';
};

export type CreateRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type CreateRoomError = CreateRoomErrors[keyof CreateRoomErrors];

export type CreateRoomResponses = {
    /**
     * OK
     */
    200: RoomResponse;
};

export type CreateRoomResponse = CreateRoomResponses[keyof CreateRoomResponses];

export type GetRoomData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: string;
    };
    query?: never;
    url: '/api/rooms/{room_id}';
};

export type GetRoomErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type GetRoomError = GetRoomErrors[keyof GetRoomErrors];

export type GetRoomResponses = {
    /**
     * OK
     */
    200: RoomResponse;
};

export type GetRoomResponse = GetRoomResponses[keyof GetRoomResponses];

export type PreviewContextData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: string;
        /**
         * Agent name
         */
        agent_name: string;
    };
    query?: {
        /**
         * Include cross-room feed
         */
        include_cross_room?: boolean;
        /**
         * Include queued interjections
         */
        include_interjections?: boolean;
    };
    url: '/api/rooms/{room_id}/agents/{agent_name}/context-preview';
};

export type PreviewContextErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type PreviewContextError = PreviewContextErrors[keyof PreviewContextErrors];

export type PreviewContextResponses = {
    /**
     * OK
     */
    200: GetContextPreviewResponseBody;
};

export type PreviewContextResponse = PreviewContextResponses[keyof PreviewContextResponses];

export type ListMessagesData = {
    body?: never;
    path: {
        /**
         * Room ID
         */
        room_id: string;
    };
    query?: {
        /**
         * Max messages to return
         */
        limit?: number;
        /**
         * Cursor: only messages before this RFC3339 timestamp
         */
        before?: string;
    };
    url: '/api/rooms/{room_id}/messages';
};

export type ListMessagesErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type ListMessagesError = ListMessagesErrors[keyof ListMessagesErrors];

export type ListMessagesResponses = {
    /**
     * OK
     */
    200: ListMessagesResponseBody;
};

export type ListMessagesResponse = ListMessagesResponses[keyof ListMessagesResponses];

export type SendMessageData = {
    body: SendMessageRequestBodyWritable;
    path: {
        /**
         * Room ID
         */
        room_id: string;
    };
    query?: never;
    url: '/api/rooms/{room_id}/messages';
};

export type SendMessageErrors = {
    /**
     * Error
     */
    default: ErrorModel;
};

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors];

export type SendMessageResponses = {
    /**
     * OK
     */
    200: MessageResponse;
};

export type SendMessageResponse = SendMessageResponses[keyof SendMessageResponses];
